// Navigation:
export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const GENERIC_MODAL_OPEN = "GENERIC_MODAL_OPEN";
export const GENERIC_MODAL_CLOSE = "GENERIC_MODAL_CLOSE";

// Homepage:
export const GET_HOMEPAGE = "GET_HOMEPAGE";
export const GET_HOMEPAGE_SUCCESS = "GET_HOMEPAGE_SUCCESS";
export const GET_HOMEPAGE_ERROR = "GET_HOMEPAGE_ERROR";
